### PR TITLE
shadowMapping: remove viewMatrix inversion (fixed by #271)

### PR DESCRIPTION
**Pull request by microaaron**
#268

https://github.com/webgpu/webgpu-samples/assets/16946786/4ee43d01-cc8a-41aa-b9a3-41fde87c9722

### CODE REVIEW

**Review by kainino0x — CHANGES_REQUESTED** [review]
It renders correctly before this patch, and incorrectly afterward. I can't tell offhand why these inverses are here, and I don't know if they can be removed. But if they can, more work is needed on this PR.

**Comment by microaaron** [comment]
> It renders correctly before this patch, and incorrectly afterward. I can't tell offhand why these inverses are here, and I don't know if they can be removed. But if they can, more work is needed on this PR.

It seems to be alright after removing these inverses.

**Comment by kainino0x** [comment]
I checked out your PR and found that it broke the rendering like so. Is your build updating correctly when you make code changes? It should do so automatically if you use `npm start`.
image

**Comment by microaaron** [comment]
The build process seems to have made some changes to the source code, I'm not sure. I copied these source codes into a js file and ran it in the browser, and found this problem. But building according to the official method seems to be no problem.

**Comment by microaaron** [comment]
Here is the example: [https://jsitor.com/r9ip6WtPnl](https://jsitor.com/r9ip6WtPnl). Key codes: line 408,411,483.

**Comment by kainino0x** [comment]
The difference seems to be between wgpu-matrix 1.x and wgpu-matrix 2.x.

@greggman should we upgrade the samples to 2.x?

**Comment by greggman** [comment]
If they're using wgpu-matrix then yes, and the breaking change from 1.x to 2.x is `mat4.lookAt` returns a view matrix (like other math libs).

**Comment by microaaron** [comment]
Fixed by #271.

**Pull request closed without merging**
